#!/bin/bash

 
export CC=gcc
export LD=gcc

echo ""
echo "****************************************************************"
echo "*          creating opcode decoding speedup tables             *"
echo "****************************************************************"
echo ""

cd opcode_table_generator
cp create_tables.win32 create_tables.sh
cp makefile.win32 makefile
./create_tables.sh
cd ..

echo ""
echo "****************************************************************"
echo "*                   compiling few tools                        *"
echo "****************************************************************"
echo ""

cd wlab
cp makefile.win32 makefile
make 
cp wlab.exe ../binaries
make clean
cd ..

cd wlad
cp makefile.win32 makefile
make 
cp wlad.exe ../binaries
make clean
cd ..

echo ""
echo "****************************************************************"
echo "*                  compiling WLA binaries                      *"
echo "****************************************************************"
echo ""

make clean
cp makefiles/makefile.win32.gb makefile
make 
cp wla-gb.exe binaries

make clean
cp makefiles/makefile.win32.z80 makefile
make 
cp wla-z80.exe binaries

make clean
cp makefiles/makefile.win32.6502 makefile
make 
cp wla-6502.exe binaries

make clean
cp makefiles/makefile.win32.65c02 makefile
make 
cp wla-65c02.exe binaries

make clean
cp makefiles/makefile.win32.6510 makefile
make 
cp wla-6510.exe binaries

make clean
cp makefiles/makefile.win32.65816 makefile
make 
cp wla-65816.exe binaries

make clean
cp makefiles/makefile.win32.spc700 makefile
make 
cp wla-spc700.exe binaries

make clean
cp makefiles/makefile.win32.huc6280 makefile
make 
cp wla-huc6280.exe binaries

make clean

echo ""
echo "****************************************************************"
echo "*                    compiling WLALINK                         *"
echo "****************************************************************"
echo ""

cd wlalink
cp makefile.win32 makefile
make 
cp wlalink.exe ../binaries
make clean
cd ..

echo ""
echo "****************************************************************"
echo "*        all done! check ./binaries/ for the results           *"
echo "****************************************************************"
echo ""
