
CC = gcc
CFLAGS = -c -ansi -O3 -pedantic -Wall
LD = gcc
LDFLAGS = 

CFILES = main.c
HFILES = main.h
OFILES = main.o

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) -o icopy.exe

main.o: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	rm -f $(OFILES) *~ icopy.exe

install:
	make ; cp icopy.exe /usr/local/bin
