CC = gcc
CFLAGS = -c -O3 -ansi -pedantic-errors -Wall -Wextra 
LD = gcc
LDFLAGS = 
RM = rm -f 
RMFLAGS = 

CFILES = main.c
HFILES = main.h
OFILES = main.o

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) -o wlad -lm

main.o: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	$(RM) $(RMFLAGS) $(OFILES) *~ wlad

install:
	make  
	install wlad /usr/local/bin
