CC = gcc
CFLAGS = -c -O3 -ansi -pedantic-errors -Wall -Wextra 
LD = gcc
LDFLAGS = -s
RM = rm -f 
RMFLAGS = 
CFILES = main.c
HFILES = main.h
OFILES = main.o

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) -o wlad.exe 

main.o: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	$(RM) $(RMFLAGS) $(OFILES) *~ wlad.exe

install:
	make 
	install wlad.exe /c/bin
