CC = cl
CFLAGS = /c /Ox /Za /W2 /nologo
LD = link
LDFLAGS = /nologo
RM = del 

CFILES = main.c
HFILES = main.h
OFILES = main.obj

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) /out:wlad.exe

main.obj: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	$(RM) -f $(OFILES) *~ wlad.exe

install:
	make ; cp wlad.exe /usr/local/bin
