
CC = cl
CFLAGS = /c /Ox /Za /W4 /DMSDOS /DGB
LD = link
LDFLAGS = 

CFILES = main.c
HFILES = main.h
OFILES = main.obj

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) /out:wlad.exe

main.obj: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	del $(OFILES) *~ wlad.exe

install:
	make ; cp wlad.exe /usr/local/bin
