CC = cl
CFLAGS = /c /Ox /Za /W2 /nologo
LD = link
LDFLAGS = /nologo
RM = del 
RMFLAGS = 
CFILES = main.c
HFILES = main.h
OFILES = main.obj

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) /out:wlad.exe 

main.obj: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	$(RM) $(RMFLAGS) $(OFILES) *~ wlad.exe

install:
	nmake 
	copy wlad.exe C:\bin
