CC=cl
LD=link
CFLAGS = /c /Ox /Za /W2 /nologo /DMSDOS /DWIN32 /D$(WLA_TARGET) /DQUIET=$(WLA_QUIET)
LDFLAGS = /nologo 
RM = del 
RMFLAGS = 
CFILES = main.c
OFILES = main.obj



all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) /out:gen.exe 

main.obj: main.c makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(CFILES)


clean:
	$(RM) $(RMFLAGS) $(OFILES) core *~ gen
