
CC=cl
LD=link
CFLAGS = /c /Ox /Za /W2 /nologo /DMSDOS /DWIN32 /D$(WLA_TARGET) /DQUIET=$(WLA_QUIET)
LDFLAGS = /nologo 
RM = del 

CFILES = main.c
OFILES = main.obj



all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) /out:gen

main.obj: main.c makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(CFILES)


clean:
	$(RM) $(OFILES) core *~ gen
