
CC = gcc
CFLAGS = -c -ansi -O3 -pedantic -Wall -DGB
LD = gcc
LDFLAGS = 

CFILES = main.c
HFILES = main.h
OFILES = main.o

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) -o wlad

main.o: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	rm *.o

install:
	make ; cp wlad /usr/local/bin
