CC = gcc
CFLAGS = -c -O3 -ansi -pedantic-errors -Wall -Wextra 
LD = gcc
LDFLAGS = 
RM = rm -f 

CFILES = main.c
HFILES = main.h
OFILES = main.o

all: $(OFILES) makefile
	$(LD) $(LDFLAGS) $(OFILES) -owlab.exe

main.o: main.c main.h makefile
	$(CC) $(CFLAGS) main.c


$(OFILES): $(HFILES)


clean:
	$(RM) -f $(OFILES) *~ wlad.exe

install:
	make ; cp wlad.exe /usr/local/bin
